changelogs/patch.rst
system/ee/EllisLab/ExpressionEngine/View/_shared/form/field.php

Just a quick fix on a typo in the shared form view.

Fix class not added to select field type

---

changelogs/minor.rst
system/ee/EllisLab/ExpressionEngine/Service/Model/Relation/HasAndBelongsToMany.php

I originally posted this on the bug tracker [here](https://expressionengine.com/support/bugs/23722/foreign-inverse-hasandbelongstomany-relationships-dont-work).
When creating a foreign hasAndBelongsToMany relationship to a native EE model, EE fails to generate the pivot table on the inverse side.
The example below shows the add-on code that is currently failing:
```php
protected static $_relationships = array(
'Channels' => array(
'type'    => 'hasAndBelongsToMany',
'model'   => 'ee:Channel',
'pivot'   => array(
'table' => 'my_addon_campaigns_channels',
'left'  => 'campaign_id',
),
'weak'    => true,
'inverse' => array(
'name' => 'Campaigns',
'type' => 'hasAndBelongsToMany',
),
),
);
```
It fails with the following error message:
```
Undefined index: pivot …
```

Fix foreign inverse HasAndBelongstoMany relationships

---

changelogs/patch.rst
system/ee/legacy/models/relationship_model.php

When the relationships_query hook is called multiple times from within Bloqs, once for each instance of a block, the first query is fine, but subsequent queries are malformed. 
I can't find a way to fix this in Bloqs, b/c the SQL string passed to the hook is malformed before Bloqs even gets to handle it.
Good query:
```SELECT DISTINCT L0.field_id as L0_field, L0.grid_field_id as L0_grid_field_id, L0.grid_col_id as L0_grid_col_id, L0.grid_row_id as L0_grid_row_id, L0.parent_id AS L0_parent, L0.child_id as L0_id, L0.order
FROM (`exp_relationships` as L0)
LEFT JOIN `exp_relationships` as L1 ON `L0`.`child_id` = `L1`.`parent_id` OR L1.parent_id = NULL
WHERE `L0`.`fluid_field_data_id` =  0
AND `L0`.`grid_field_id` =  0
AND `L0`.`parent_id` IN (540) 
ORDER BY `L0`.`order` asc
```
Malformed …

Fix a potential malformed query issue in the relationships_query hook 

---

changelogs/patch.rst
system/ee/EllisLab/Addons/url/ft.url.php

This addresses a feature/bug fix (hence `feaug`) to allow `mailto:` as an optional protocol in URL fields.
User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/19

Allow mailto: as an optional protocol in URL fields

---

system/ee/EllisLab/ExpressionEngine/Controller/Design/Template.php
system/ee/EllisLab/ExpressionEngine/Controller/Publish/AbstractPublish.php

Users are more likely to want to compare and work with recent revisions than older ones. Therefore, the revisions list should start with the most recent revisions (the same way that the entries list shows recent entries and the file list show recent files).
Resolves [#NN](https://github.com/ExpressionEngine/ExpressionEngine/issues/NN).
- [x ] 🚀 Implements a new feature
- [x ] Yes

Sort revisions by edit_date/rev_date desc

---

changelogs/patch.rst
system/ee/EllisLab/Addons/simple_commerce/mcp.simple_commerce.php

Fixes #119
- [x ] 🐛 Fixes a bug
- [x ] Yes

Correctly humanise subscription end date

---

changelogs/patch.rst
system/ee/legacy/language/english/core_lang.php

The language file showed a hard coded file path during a permission error, i've changed it to use dynamic system path variable.
Resolves [#NN](https://github.com/ExpressionEngine/ExpressionEngine/issues/NN).

correct system paths in language file

---

changelogs/patch.md
system/ee/EllisLab/Addons/search/mod.search.php

Addresses this bug: https://github.com/ExpressionEngine/ExpressionEngine/issues/141 plus the absolute_count wasn't working properly. 
Resolves [#141](https://github.com/ExpressionEngine/ExpressionEngine/issues/141).

Search module absolute counts were wrong.

---

system/ee/EllisLab/ExpressionEngine/Model/Member/Member.php
system/ee/legacy/language/english/cp_lang.php

Altered notifications when hash alogrithms cause a password hash update.  Related to issue #170 but this is a more general behavior change. That particular bug is already fixed.

Altered password change notifications related to hash algorithm changes.

---

system/ee/EllisLab/ExpressionEngine/Controller/Addons/Addons.php

Modify the anchor tag to link from add-ons to their manuals 
https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/EllisLab/ExpressionEngine/Controller/Addons/Addons.php
line 348
- [ x] 🐛 Fixes a bug
- [ x] 💅 Fixes coding style
- [x ] Yes

Modify the anchor tag to link from add-ons to their manuals 

---

changelogs/patch.md
system/ee/EllisLab/Addons/rte/ext.rte.php
system/ee/EllisLab/ExpressionEngine/Controller/Settings/HitTracking.php
system/ee/EllisLab/ExpressionEngine/Controller/Settings/SecurityPrivacy.php

Updates hardcoded docs links in the Control Panel to use the `DOCS_URL` constant.
Resolves [#224](https://github.com/ExpressionEngine/ExpressionEngine/issues/224).

Control panel links update to not point to v4/ docs, but to latest docs

---

system/ee/EllisLab/ExpressionEngine/Model/Channel/Channel.php

The Channel model does not currently publish even hooks when a channel is created, updated, or deleted. As an add-on developer it would be nice to be able to subscribe to these events.

Add hook_id to Channel model

---

changelogs/minor.rst
system/ee/EllisLab/ExpressionEngine/Config/mimes.php

On some servers, the mime type for `svg` is reported as `image/svg` and not as the expected `image/svg+xml` which result in not able to upload SVG files.
By adding just a new mime type without the `+xml` should fix this issue.
Resolves [#139](https://github.com/ExpressionEngine/ExpressionEngine/issues/139).
- changelogs/minor.rst (x.X.x)

Added extra mime for SVG as some servers report SVG without +xml

---

system/ee/EllisLab/Addons/member/mod.member.php

Fixes join_date variable in mod.member.php, addresses #272 
Resolves [#272](https://github.com/ExpressionEngine/ExpressionEngine/issues/272).

Fixing join_date variable name, addresses #272

---

system/ee/legacy/libraries/Filemanager.php

Addresses an issue where images are rotated improperly because of how phones use exif data to handle presentation.  This orientation check looks at the exif data and if it indicates the image needs to be rotated, it rotates it and saves the new image.  See discussion  https://expressionengine.com/forums/topic/252416/how-do-i-upload-images-and-resize-them-without-ee-rotating-them
Halfway between a bug fix and a feature.  The code worked as intended, but the result could be unintended.

Added an exif check for image rotation when uploading or saving an image

---

changelogs/minor.rst
system/ee/EllisLab/ExpressionEngine/Model/Channel/Channel.php
system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelFormSettings.php
system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelLayout.php
system/ee/EllisLab/ExpressionEngine/Model/Site/Site.php
system/ee/EllisLab/ExpressionEngine/Model/Status/Status.php
system/ee/EllisLab/ExpressionEngine/Model/Template/GlobalVariable.php
system/ee/EllisLab/ExpressionEngine/Model/Template/Snippet.php
system/ee/EllisLab/ExpressionEngine/Model/Template/SpecialtyTemplate.php

Add new/additional event hooks to ChannelFormSettings, ChannelLayout, Site, GlobalVariable, Snippet, Status, and SpecialtyTemplate models.
User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/52

Add additional hooks to Channel, Site, and Template models

---

changelogs/patch.md
system/ee/EllisLab/ExpressionEngine/Service/Formatter/Formats/Text.php
system/ee/EllisLab/Tests/ExpressionEngine/Service/Formatter/TextFormatterTest.php

Fix a bug where the _lowercase_ parameter of the `:url_slug` variable modifier wasn't being applied.
This fix modifies the `Formatter\Text` class, specifically the `urlSlug()` method, and simply adds the `get_bool_from_string()` function to the _lowercase_ option check. Without this, the check always fails and the option (ie. the parameter to the `:url_slug` variable modifier) always defaults, rendering the option unusable.

Fix a bug with the :url_slug variable modifier

---

system/ee/legacy/libraries/Typography.php

Removes type="text/javascript" attribute from {encode} script, which makes code valid at [The W3C Markup Validation Service](https://validator.w3.org/nu/).
Resolves [#306](https://github.com/ExpressionEngine/ExpressionEngine/issues/306).
- [x ] 💅 Fixes coding style
- [ x] 🔥 Removes unused files / code
- [x ] Yes
- changelogs/minor.rst (5.3.0)

Remove type attribute from {encode} script

---

system/ee/installer/updater/boot.php

when using 1-click updater
When performing 1-click update on Windows, one was getting this error: `Log file path not writable: C:\inetpub\wwwroot\ee531\system/user/cache/ee_update`
The reason is code referencing undefined constants in libraries used in updater. This add all EE constants to updater boot file
- [x ] 🐛 Fixes a bug
- [x ] Yes

fixes "Log file path not writable" error on Windows 

---

system/ee/EllisLab/ExpressionEngine/View/utilities/extensions.php

On the Debug Extensions page, if short tags is not on, the pagination would not show. I fixed the opening php tag.
I have a lot of extensions, and at a certain point, I was pulling my beard out trying to figure out why some extensions were not showing on the Debug Extensions page. I realized there was no pagination. I noticed that this line used the short open tags, and I don't have short_open_tag enabled. Converted it to a full php open tag.
https://docs.expressionengine.com/latest/bugs_and_security_reports -->

Fix php opening tag

---

system/ee/legacy/libraries/Filemanager.php

Uploading files was not possible on Windows due to wrong variable name used in legacy Filemanager library for setting the path. This commit is fixing it.

Use correct variable name in Filemanager to avoid thumb creation error on Windows

---

system/ee/EllisLab/ExpressionEngine/Controller/Fields/Fields.php

Make sure a valid field name is submitted when creating a new field.

make sure field names are valid

---

changelogs/patch.md
system/ee/EllisLab/ExpressionEngine/Service/Memory/Memory.php

On php 7.4 user was getting a php warning trying to upload images:
> Trying to access array offset on value of type bool
> ee/EllisLab/ExpressionEngine/Service/Memory/Memory.php, line 45
If we don't have all of the info from @getimagesize() that we need to calculate a memory requirement estimate, I just returned.

Fixed a php 7.4 warning when trying to set memory for file uploads.

---

changelogs/minor.md
system/ee/EllisLab/ExpressionEngine/Service/Alert/Alert.php
system/ee/legacy/libraries/Cp.php

Added 3rd parameter (`bool`) for `addToBody` function in CP/Alert that allows disabling filtering for particular message

improve handling CP alerts

---

changelogs/patch.md
system/ee/EllisLab/ExpressionEngine/Controller/Settings/General.php

Fixed a bug where PHP error was thrown in some cases during check for available updates.
Resolves [#416](https://github.com/ExpressionEngine/ExpressionEngine/issues/416).

ensures we have version info to check against for updates #416

---

system/ee/EllisLab/ExpressionEngine/Cli/Cli.php

Removes commands for 6.0 for inclusion in 5.4

Removing commands for 5.4

---

changelogs/patch.md
system/ee/EllisLab/Addons/consent/mod.consent.php

If you didn't specify a return parameter, it should have returned to the page it was submitted from, but it always returned to the homepage.

Fixed the consent form's return behavior.

---

changelogs/patch.md
system/ee/legacy/fieldtypes/EE_Fieldtype.php

Fixes an issue with the Channel Field "Select Dropdown" option to "Populate the menu from another channel field". The `->fields()` call on the model retrieval was missing the `CF.field_name` (used by the later `$channel->getAllCustomFields()` and `CF.field_type` (used to check compatibility) fields causing no options to show up for this setting.

Added missing fields from model retrieval (used by getAllCustomFields)

---

changelogs/patch.md
system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelField.php

Before, it just left the settings, which really shouldn’t have mattered.  But it was causing Asset fields to continue to display as Asset fields on publish, even after changing to File fields.  The setting fields also didn’t display on the file field’d edit page. Fixes https://github.com/ExpressionEngine/ExpressionEngine/issues/618
Cleaning them out on save just makes sense.

Changing a custom field type now resets the field settings.
